# Generated by Django 5.2.4 on 2025-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Сокращение'),
        ),
    ]
