# Generated by Django 5.2.4 on 2025-10-20 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('SUPERUSER', 'Супер-администратор'), ('GENERAL_DIRECTOR', 'Генеральный директор'), ('DIRECTOR', 'Директор'), ('EXPERT', 'Эксперт'), ('TEACHER', 'Учитель'), ('HOMEROOM_TEACHER', 'Классный руководитель'), ('STUDENT', 'Ученик')], default='TEACHER', max_length=20, verbose_name='Роль')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фотография')),
                ('homeroom_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher_profile', to='core.schoolclass', verbose_name='Классное руководство')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='core.school', verbose_name='Школа (для Учителя)')),
                ('schools', models.ManyToManyField(blank=True, related_name='director_profiles', to='core.school', verbose_name='Доступ к школам (для Директора)')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.student')),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject', verbose_name='Предметы (для Учителя/Эксперта)')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
